import { Agent, PricingPlan, Review, User, Subscription, UsageRecord } from '@/types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'CodeMaster Pro',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=codemaster',
    tagline: '全栈代码助手，支持50+编程语言',
    description: 'CodeMaster Pro 是一款强大的AI编程助手，支持代码生成、调试、重构和代码审查。支持Python、JavaScript、TypeScript、Go、Rust等50+编程语言。',
    category: '开发工具',
    tags: ['编程', '代码生成', 'Debug'],
    rating: 4.8,
    reviewCount: 1256,
    callCount: 89420,
    priceType: 'per_use',
    priceDisplay: '¥0.02/次',
    reliabilityGrade: 'A',
    successRate: 99.2,
    avgResponseTime: 1.2,
    uptime: 99.9,
    isVerified: true,
    isFeatured: true,
    creatorName: 'TechForge Lab',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=techforge',
    capabilities: ['代码生成', '代码审查', 'Bug修复', '单元测试'],
    modelBase: 'Claude 3.5 Sonnet',
  },
  {
    id: '2',
    name: '文案大师',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=copywriter',
    tagline: '专业营销文案，一键生成爆款内容',
    description: '文案大师专注于营销文案创作，支持小红书、抖音、公众号等多平台风格，让你的内容轻松出圈。',
    category: '内容创作',
    tags: ['文案', '营销', '小红书'],
    rating: 4.6,
    reviewCount: 892,
    callCount: 45230,
    priceType: 'subscription',
    priceDisplay: '¥29/月',
    reliabilityGrade: 'A',
    successRate: 98.5,
    avgResponseTime: 2.1,
    uptime: 99.5,
    isVerified: true,
    isFeatured: false,
    creatorName: '创意工坊',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=creative',
    capabilities: ['营销文案', '种草笔记', '视频脚本', '标题优化'],
    modelBase: 'GPT-4o',
  },
  {
    id: '3',
    name: 'DataInsight',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=datainsight',
    tagline: '智能数据分析，秒出可视化报告',
    description: '上传数据，自动生成分析报告和可视化图表。支持Excel、CSV、JSON等格式，让数据说话。',
    category: '数据分析',
    tags: ['数据', '报表', '可视化'],
    rating: 4.5,
    reviewCount: 567,
    callCount: 23100,
    priceType: 'per_use',
    priceDisplay: '¥0.05/次',
    reliabilityGrade: 'B',
    successRate: 94.2,
    avgResponseTime: 3.5,
    uptime: 98.0,
    isVerified: false,
    isFeatured: false,
    creatorName: '数据魔方',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=datacube',
    capabilities: ['数据清洗', '统计分析', '图表生成', '趋势预测'],
    modelBase: 'Claude 3 Opus',
  },
  {
    id: '4',
    name: '法律顾问AI',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=lawyer',
    tagline: '专业法律咨询，合同审查一键搞定',
    description: '基于中国法律法规训练，提供合同审查、法律咨询、文书起草等服务。已通过司法考试模拟测试。',
    category: '专业服务',
    tags: ['法律', '合同', '咨询'],
    rating: 4.9,
    reviewCount: 234,
    callCount: 8920,
    priceType: 'per_use',
    priceDisplay: '¥0.10/次',
    reliabilityGrade: 'A',
    successRate: 99.5,
    avgResponseTime: 2.8,
    uptime: 99.8,
    isVerified: true,
    isFeatured: true,
    creatorName: '智法科技',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=lawtech',
    capabilities: ['合同审查', '法律咨询', '文书起草', '风险评估'],
    modelBase: 'GPT-4 Turbo',
  },
  {
    id: '5',
    name: 'DesignBot',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=designer',
    tagline: 'UI设计助手，快速出图不求人',
    description: '专业UI/UX设计助手，支持原型设计、配色方案、组件建议等，让设计更高效。',
    category: '设计工具',
    tags: ['UI设计', '配色', '原型'],
    rating: 4.3,
    reviewCount: 445,
    callCount: 15670,
    priceType: 'subscription',
    priceDisplay: '¥49/月',
    reliabilityGrade: 'B',
    successRate: 92.1,
    avgResponseTime: 4.2,
    uptime: 97.5,
    isVerified: false,
    isFeatured: false,
    creatorName: 'PixelPerfect',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=pixel',
    capabilities: ['UI建议', '配色方案', '组件设计', '设计规范'],
    modelBase: 'Claude 3.5 Sonnet',
  },
  {
    id: '6',
    name: '翻译官Pro',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=translator',
    tagline: '专业多语言翻译，支持100+语种',
    description: '高质量AI翻译，支持中英日韩法德等100+语种互译，专业术语精准，保留原文风格。',
    category: '语言工具',
    tags: ['翻译', '多语言', '本地化'],
    rating: 4.7,
    reviewCount: 2103,
    callCount: 156000,
    priceType: 'free',
    priceDisplay: '免费',
    reliabilityGrade: 'A',
    successRate: 98.8,
    avgResponseTime: 0.8,
    uptime: 99.9,
    isVerified: true,
    isFeatured: true,
    creatorName: 'LangBridge',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=langbridge',
    capabilities: ['实时翻译', '文档翻译', '术语管理', '风格保持'],
    modelBase: 'GPT-4o',
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'basic',
    name: '按次计费',
    price: 0.02,
    unit: '次',
    quota: null,
    features: ['即用即付', '无最低消费', '7天使用记录'],
    isRecommended: false,
  },
  {
    id: 'pro',
    name: '专业版',
    price: 29,
    unit: '月',
    quota: 1000,
    features: ['1000次/月', '优先响应', '30天使用记录', '专属客服'],
    isRecommended: true,
  },
  {
    id: 'unlimited',
    name: '无限版',
    price: 99,
    unit: '月',
    quota: null,
    features: ['无限次调用', '最优先响应', '完整历史记录', '1对1技术支持', 'API访问'],
    isRecommended: false,
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    userId: 'u1',
    userName: '码农小王',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wang',
    rating: 5,
    content: '代码生成质量很高，节省了大量时间！特别是单元测试生成功能，太实用了。',
    createdAt: '2026-02-20',
    helpful: 42,
  },
  {
    id: '2',
    userId: 'u2',
    userName: '全栈老李',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=li',
    rating: 4,
    content: '整体不错，偶尔会有一些小bug需要手动修复，但瑕不掩瑜。',
    createdAt: '2026-02-18',
    helpful: 28,
  },
  {
    id: '3',
    userId: 'u3',
    userName: '前端萌新',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=newbie',
    rating: 5,
    content: '对新手太友好了！不仅生成代码，还会解释每一行的作用。强烈推荐！',
    createdAt: '2026-02-15',
    helpful: 56,
  },
];

export const mockUser: User = {
  id: 'current-user',
  username: 'test_user',
  displayName: '测试用户',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=testuser',
  email: 'test@example.com',
  balance: 128.50,
  role: 'user',
};

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub1',
    agentId: '1',
    agentName: 'CodeMaster Pro',
    agentAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=codemaster',
    planName: '专业版',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2026-03-01',
    used: 423,
    total: 1000,
  },
  {
    id: 'sub2',
    agentId: '2',
    agentName: '文案大师',
    agentAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=copywriter',
    planName: '无限版',
    status: 'active',
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    used: 156,
    total: null,
  },
];

export const mockUsageRecords: UsageRecord[] = [
  { id: 'r1', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 17:30:21', status: 'success', responseTime: 1.2, cost: 0.02 },
  { id: 'r2', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 16:45:10', status: 'success', responseTime: 0.9, cost: 0.02 },
  { id: 'r3', agentId: '2', agentName: '文案大师', timestamp: '2026-02-23 15:20:33', status: 'success', responseTime: 2.3, cost: 0 },
  { id: 'r4', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 14:10:05', status: 'failed', responseTime: 5.0, cost: 0 },
  { id: 'r5', agentId: '6', agentName: '翻译官Pro', timestamp: '2026-02-23 12:30:00', status: 'success', responseTime: 0.6, cost: 0 },
];

export const categories = [
  '全部',
  '开发工具',
  '内容创作',
  '数据分析',
  '专业服务',
  '设计工具',
  '语言工具',
  '效率工具',
  '教育学习',
];
