import { Agent, PricingPlan, Review, User, Subscription, UsageRecord, Bounty, BountyUser, Video } from '@/types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'CodeMaster Pro',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=codemaster',
    tagline: '全栈代码助手，支持50+编程语言',
    description: 'CodeMaster Pro 是一款强大的AI编程助手，支持代码生成、调试、重构和代码审查。支持Python、JavaScript、TypeScript、Go、Rust等50+编程语言。',
    category: '开发工具',
    tags: ['编程', '代码生成', 'Debug'],
    rating: 4.8,
    reviewCount: 1256,
    callCount: 89420,
    priceType: 'per_use',
    priceDisplay: '¥0.02/次',
    reliabilityGrade: 'A',
    successRate: 99.2,
    avgResponseTime: 1.2,
    uptime: 99.9,
    isVerified: true,
    isFeatured: true,
    creatorName: 'TechForge Lab',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=techforge',
    capabilities: ['代码生成', '代码审查', 'Bug修复', '单元测试'],
    modelBase: 'Claude 3.5 Sonnet',
  },
  {
    id: '2',
    name: '文案大师',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=copywriter',
    tagline: '专业营销文案，一键生成爆款内容',
    description: '文案大师专注于营销文案创作，支持小红书、抖音、公众号等多平台风格，让你的内容轻松出圈。',
    category: '内容创作',
    tags: ['文案', '营销', '小红书'],
    rating: 4.6,
    reviewCount: 892,
    callCount: 45230,
    priceType: 'subscription',
    priceDisplay: '¥29/月',
    reliabilityGrade: 'A',
    successRate: 98.5,
    avgResponseTime: 2.1,
    uptime: 99.5,
    isVerified: true,
    isFeatured: false,
    creatorName: '创意工坊',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=creative',
    capabilities: ['营销文案', '种草笔记', '视频脚本', '标题优化'],
    modelBase: 'GPT-4o',
  },
  {
    id: '3',
    name: 'DataInsight',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=datainsight',
    tagline: '智能数据分析，秒出可视化报告',
    description: '上传数据，自动生成分析报告和可视化图表。支持Excel、CSV、JSON等格式，让数据说话。',
    category: '数据分析',
    tags: ['数据', '报表', '可视化'],
    rating: 4.5,
    reviewCount: 567,
    callCount: 23100,
    priceType: 'per_use',
    priceDisplay: '¥0.05/次',
    reliabilityGrade: 'B',
    successRate: 94.2,
    avgResponseTime: 3.5,
    uptime: 98.0,
    isVerified: false,
    isFeatured: false,
    creatorName: '数据魔方',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=datacube',
    capabilities: ['数据清洗', '统计分析', '图表生成', '趋势预测'],
    modelBase: 'Claude 3 Opus',
  },
  {
    id: '4',
    name: '法律顾问AI',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=lawyer',
    tagline: '专业法律咨询，合同审查一键搞定',
    description: '基于中国法律法规训练，提供合同审查、法律咨询、文书起草等服务。已通过司法考试模拟测试。',
    category: '专业服务',
    tags: ['法律', '合同', '咨询'],
    rating: 4.9,
    reviewCount: 234,
    callCount: 8920,
    priceType: 'per_use',
    priceDisplay: '¥0.10/次',
    reliabilityGrade: 'A',
    successRate: 99.5,
    avgResponseTime: 2.8,
    uptime: 99.8,
    isVerified: true,
    isFeatured: true,
    creatorName: '智法科技',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=lawtech',
    capabilities: ['合同审查', '法律咨询', '文书起草', '风险评估'],
    modelBase: 'GPT-4 Turbo',
  },
  {
    id: '5',
    name: 'DesignBot',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=designer',
    tagline: 'UI设计助手，快速出图不求人',
    description: '专业UI/UX设计助手，支持原型设计、配色方案、组件建议等，让设计更高效。',
    category: '设计工具',
    tags: ['UI设计', '配色', '原型'],
    rating: 4.3,
    reviewCount: 445,
    callCount: 15670,
    priceType: 'subscription',
    priceDisplay: '¥49/月',
    reliabilityGrade: 'B',
    successRate: 92.1,
    avgResponseTime: 4.2,
    uptime: 97.5,
    isVerified: false,
    isFeatured: false,
    creatorName: 'PixelPerfect',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=pixel',
    capabilities: ['UI建议', '配色方案', '组件设计', '设计规范'],
    modelBase: 'Claude 3.5 Sonnet',
  },
  {
    id: '6',
    name: '翻译官Pro',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=translator',
    tagline: '专业多语言翻译，支持100+语种',
    description: '高质量AI翻译，支持中英日韩法德等100+语种互译，专业术语精准，保留原文风格。',
    category: '语言工具',
    tags: ['翻译', '多语言', '本地化'],
    rating: 4.7,
    reviewCount: 2103,
    callCount: 156000,
    priceType: 'free',
    priceDisplay: '免费',
    reliabilityGrade: 'A',
    successRate: 98.8,
    avgResponseTime: 0.8,
    uptime: 99.9,
    isVerified: true,
    isFeatured: true,
    creatorName: 'LangBridge',
    creatorAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=langbridge',
    capabilities: ['实时翻译', '文档翻译', '术语管理', '风格保持'],
    modelBase: 'GPT-4o',
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'basic',
    name: '按次计费',
    price: 0.02,
    unit: '次',
    quota: null,
    features: ['即用即付', '无最低消费', '7天使用记录'],
    isRecommended: false,
  },
  {
    id: 'pro',
    name: '专业版',
    price: 29,
    unit: '月',
    quota: 1000,
    features: ['1000次/月', '优先响应', '30天使用记录', '专属客服'],
    isRecommended: true,
  },
  {
    id: 'unlimited',
    name: '无限版',
    price: 99,
    unit: '月',
    quota: null,
    features: ['无限次调用', '最优先响应', '完整历史记录', '1对1技术支持', 'API访问'],
    isRecommended: false,
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    userId: 'u1',
    userName: '码农小王',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wang',
    rating: 5,
    content: '代码生成质量很高，节省了大量时间！特别是单元测试生成功能，太实用了。',
    createdAt: '2026-02-20',
    helpful: 42,
  },
  {
    id: '2',
    userId: 'u2',
    userName: '全栈老李',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=li',
    rating: 4,
    content: '整体不错，偶尔会有一些小bug需要手动修复，但瑕不掩瑜。',
    createdAt: '2026-02-18',
    helpful: 28,
  },
  {
    id: '3',
    userId: 'u3',
    userName: '前端萌新',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=newbie',
    rating: 5,
    content: '对新手太友好了！不仅生成代码，还会解释每一行的作用。强烈推荐！',
    createdAt: '2026-02-15',
    helpful: 56,
  },
];

export const mockUser: User = {
  id: 'current-user',
  username: 'test_user',
  displayName: '测试用户',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=testuser',
  email: 'test@example.com',
  balance: 128.50,
  role: 'user',
};

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub1',
    agentId: '1',
    agentName: 'CodeMaster Pro',
    agentAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=codemaster',
    planName: '专业版',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2026-03-01',
    used: 423,
    total: 1000,
  },
  {
    id: 'sub2',
    agentId: '2',
    agentName: '文案大师',
    agentAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=copywriter',
    planName: '无限版',
    status: 'active',
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    used: 156,
    total: null,
  },
];

export const mockUsageRecords: UsageRecord[] = [
  { id: 'r1', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 17:30:21', status: 'success', responseTime: 1.2, cost: 0.02 },
  { id: 'r2', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 16:45:10', status: 'success', responseTime: 0.9, cost: 0.02 },
  { id: 'r3', agentId: '2', agentName: '文案大师', timestamp: '2026-02-23 15:20:33', status: 'success', responseTime: 2.3, cost: 0 },
  { id: 'r4', agentId: '1', agentName: 'CodeMaster Pro', timestamp: '2026-02-23 14:10:05', status: 'failed', responseTime: 5.0, cost: 0 },
  { id: 'r5', agentId: '6', agentName: '翻译官Pro', timestamp: '2026-02-23 12:30:00', status: 'success', responseTime: 0.6, cost: 0 },
];

export const categories = [
  '全部',
  '开发工具',
  '内容创作',
  '数据分析',
  '专业服务',
  '设计工具',
  '语言工具',
  '效率工具',
  '教育学习',
];

// ==================== 悬赏系统数据 ====================

export const bountyUsers: Record<string, BountyUser> = {
  u1: { id: 'u1', name: '笑码科技', avatar: '🧑‍💻', followers: 12400, bio: 'AI智能体开发者', verified: true, type: 'company' },
  u2: { id: 'u2', name: '方达AI', avatar: '📊', followers: 8900, bio: '企业级AI解决方案', verified: true, type: 'company' },
  u3: { id: 'u3', name: 'QuickBI', avatar: '📈', followers: 5200, bio: '图表智能解读', verified: true, type: 'company' },
  u4: { id: 'u4', name: '夏日AI', avatar: '☀️', followers: 6700, bio: '创意设计AI', verified: true, type: 'individual' },
  u5: { id: 'u5', name: '时尚AI', avatar: '👗', followers: 9800, bio: '电商AI方案', verified: true, type: 'company' },
  u6: { id: 'u6', name: 'UPCV', avatar: '📄', followers: 4500, bio: '简历优化专家', verified: true, type: 'individual' },
  u7: { id: 'u7', name: '种草达人', avatar: '🌱', followers: 15600, bio: '社媒运营专家', verified: false, type: 'individual' },
  u9: { id: 'u9', name: '自动化侠', avatar: '🤖', followers: 7100, bio: 'RPA专家', verified: true, type: 'individual' },
  u10: { id: 'u10', name: '卡哇伊工坊', avatar: '🌸', followers: 11200, bio: '可爱风AI', verified: false, type: 'individual' },
  u11: { id: 'u11', name: '学霸AI', avatar: '📚', followers: 8400, bio: 'AI私教', verified: true, type: 'individual' },
};

export const mockBounties: Bounty[] = [
  {
    id: 'b1',
    title: '寻找能自动生成数据分析报告的智能体',
    reward: 50000,
    uid: 'u2',
    posterType: 'company',
    urgency: 'high',
    deadline: '2026-03-05',
    status: 'review',
    desc: '需求：自动读取Excel/CSV，生成可视化图表+专业分析报告。\n\n具体要求：\n1. 支持xlsx/csv/json多格式导入\n2. 自动识别数据类型选择最佳图表\n3. 生成摘要、趋势分析、异常检测的完整报告\n4. 支持自定义报告模板\n5. 100万行数据<30秒处理',
    tags: ['数据分析', '可视化', '报告'],
    submissions: [
      {
        id: 's1',
        uid: 'u1',
        time: '3天前',
        status: 'under_review',
        price: 45000,
        days: 14,
        pitch: '我们团队有丰富的数据可视化经验，已服务500+企业。可2周完成全部开发与测试。',
        demoUrl: 'https://demo.example.com/data-reporter',
        demoDesc: '在线Demo：支持上传CSV，实时生成图表和分析报告。已实现要求1-3，模板功能开发中。',
        tech: 'Python + Pandas + Plotly + GPT-4 + FastAPI',
        files: [{ name: '架构设计文档.pdf', size: '2.4MB' }, { name: 'API接口说明.md', size: '156KB' }],
        feedbacks: [
          { from: 'u2', text: 'Demo整体不错，但图表样式需要更专业，能否支持ECharts风格？', time: '2天前', type: 'revision' },
          { from: 'u1', text: '已更新Demo，新增5种ECharts风格图表模板，请查看。', time: '1天前', type: 'reply' },
          { from: 'u2', text: '图表样式好多了！处理速度也符合要求。准备进入交易。', time: '6小时前', type: 'approve' },
        ],
      },
      {
        id: 's2',
        uid: 'u9',
        time: '5天前',
        status: 'submitted',
        price: 48000,
        days: 10,
        pitch: '已有成熟数据分析Pipeline，支持所有要求功能。',
        demoUrl: 'https://auto-hero.dev/data-agent-demo',
        demoDesc: '完整功能Demo，上传数据后自动生成PDF报告。',
        tech: 'Node.js + D3.js + Claude API + Docker',
        files: [{ name: '演示视频.mp4', size: '45MB' }],
        feedbacks: [],
      },
    ],
  },
  {
    id: 'b2',
    title: '三平台自动化运营智能体',
    reward: 20000,
    uid: 'u7',
    posterType: 'individual',
    urgency: 'medium',
    deadline: '2026-03-10',
    status: 'open',
    desc: '自动发布内容到微信公众号+小红书+抖音，支持排期发布和数据回收分析。需根据平台特点自动调整文案和图片。',
    tags: ['自动化', '社媒运营', '多平台'],
    submissions: [],
  },
  {
    id: 'b3',
    title: '电商产品图批量生成Agent',
    reward: 35000,
    uid: 'u5',
    posterType: 'company',
    urgency: 'high',
    deadline: '2026-03-01',
    status: 'escrow',
    desc: '根据产品白底图自动生成多场景、多风格电商主图和详情页。',
    tags: ['电商', '产品图', '批量生成'],
    submissions: [
      {
        id: 's3',
        uid: 'u4',
        time: '1周前',
        status: 'accepted',
        price: 32000,
        days: 7,
        pitch: '专业电商视觉AI，支持50+场景模板。',
        demoUrl: 'https://summerai.cn/ecom-demo',
        demoDesc: '上传白底图即可预览8种场景效果',
        tech: 'Stable Diffusion + ControlNet + ComfyUI',
        files: [
          { name: '完整源码.zip', size: '128MB' },
          { name: '部署文档.md', size: '89KB' },
          { name: 'API文档.pdf', size: '1.2MB' },
        ],
        feedbacks: [
          { from: 'u5', text: '效果很好，同意进入交易。已将¥32,000托管到平台。', time: '3天前', type: 'approve' },
          { from: 'u4', text: '已提交全部源码和部署文档到平台。', time: '2天前', type: 'reply' },
        ],
        escrow: {
          buyerPaid: true,
          sellerUploaded: true,
          review: 'in_progress',
          paidTime: '3天前',
          uploadTime: '2天前',
        },
      },
    ],
  },
  {
    id: 'b4',
    title: '智能客服知识库Agent定制',
    reward: 15000,
    uid: 'u3',
    posterType: 'company',
    urgency: 'low',
    deadline: '2026-03-20',
    status: 'open',
    desc: '基于企业知识库构建智能客服，支持多轮对话、意图识别。',
    tags: ['客服', '知识库', '企业级'],
    submissions: [],
  },
  {
    id: 'b5',
    title: 'AI视频脚本+配音+剪辑',
    reward: 28000,
    uid: 'u4',
    posterType: 'individual',
    urgency: 'medium',
    deadline: '2026-03-15',
    status: 'in_progress',
    desc: '输入主题自动生成脚本、AI配音、自动剪辑输出成品。',
    tags: ['视频', '配音', '剪辑'],
    submissions: [
      {
        id: 's4',
        uid: 'u1',
        time: '4天前',
        status: 'working',
        price: 26000,
        days: 21,
        pitch: '整合多AI能力打造视频生产线。',
        demoUrl: '',
        demoDesc: '开发中，预计3天后提交Demo',
        tech: 'FFmpeg + Whisper + GPT-4 + ElevenLabs',
        files: [],
        feedbacks: [],
      },
    ],
  },
  {
    id: 'b6',
    title: '法律文书智能审核Agent',
    reward: 40000,
    uid: 'u6',
    posterType: 'individual',
    urgency: 'high',
    deadline: '2026-03-08',
    status: 'completed',
    desc: '自动审核合同，识别风险条款，生成修改建议。',
    tags: ['法律', '合同审核'],
    submissions: [
      {
        id: 's5',
        uid: 'u9',
        time: '2周前',
        status: 'completed',
        price: 38000,
        days: 14,
        pitch: '法律AI专项',
        demoUrl: 'https://auto-hero.dev/legal',
        demoDesc: '完整合同审核演示',
        tech: 'Claude + RAG + FastAPI',
        files: [
          { name: '完整源码.zip', size: '96MB' },
          { name: '使用手册.pdf', size: '3.1MB' },
        ],
        feedbacks: [{ from: 'u6', text: '非常满意！交易完成。', time: '5天前', type: 'complete' }],
        escrow: {
          buyerPaid: true,
          sellerUploaded: true,
          review: 'passed',
          paidTime: '8天前',
          uploadTime: '7天前',
          doneTime: '5天前',
        },
      },
    ],
  },
];

export const mockVideos: Video[] = [
  { id: 'v1', uid: 'u1', type: 'showcase', title: '我开发的客服智能体，3秒回答任何问题！', desc: '基于RAG技术的企业客服Agent，支持多轮对话 #智能客服 #AI实战', likes: 2340, comments: 189, shares: 67, saves: 234, gradient: 'linear-gradient(135deg,#0f0c29,#302b63,#24243e)', time: '2小时前', agentId: '1' },
  { id: 'v2', uid: 'u7', type: 'bounty', title: '【悬赏¥50,000】谁能做数据分析报告Agent？', desc: '需求详细说明，欢迎有实力的团队接单！ #悬赏 #数据分析', likes: 5670, comments: 423, shares: 312, saves: 890, gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)', time: '5小时前', bountyId: 'b1' },
  { id: 'v3', uid: 'u10', type: 'daily', title: '用AI生成了一整套表情包，朋友圈炸了😱', desc: 'Q版贴纸生成器太好玩了 #AI日常 #表情包', likes: 8920, comments: 567, shares: 234, saves: 1200, gradient: 'linear-gradient(135deg,#0d1117,#161b22,#21262d)', time: '1天前' },
  { id: 'v4', uid: 'u4', type: 'showcase', title: '多模态智能体发布！能看图听音写代码🔥', desc: '整合GPT-4V+Whisper+Code Interpreter #多模态 #全能Agent', likes: 15600, comments: 1230, shares: 890, saves: 3400, gradient: 'linear-gradient(135deg,#1b0a2e,#2d1b4e,#1a0a3e)', time: '3天前' },
  { id: 'v5', uid: 'u9', type: 'daily', title: '测评10个写作Agent，这个最能打！', desc: '横评市面写作Agent #测评 #写作AI', likes: 23400, comments: 2100, shares: 1560, saves: 5600, gradient: 'linear-gradient(135deg,#0a0a0a,#1a1a2e,#0d1b2a)', time: '5天前' },
];
